package com.example.gymmanagement.shop;
import org.junit.jupiter.api.*;import static org.junit.jupiter.api.Assertions.*;import static org.mockito.Mockito.*;import org.springframework.mock.env.MockEnvironment;import com.fasterxml.jackson.databind.ObjectMapper;import java.util.*;import java.time.*;
class ShopPaymentTest {
 StoreOrderRepository orders;ShopAuditService audit;ShopPaymentService payments;StoreOrder order;MockEnvironment env;
 @BeforeEach void init(){orders=mock(StoreOrderRepository.class);audit=mock(ShopAuditService.class);env=new MockEnvironment().withProperty("shop.payment.momo.enabled","true").withProperty("shop.payment.momo.partner-code","test-partner").withProperty("shop.payment.momo.access-key","test-access").withProperty("shop.payment.momo.secret-key","test-secret").withProperty("shop.payment.backend-url","https://merchant.example.test").withProperty("shop.payment.return-url","https://merchant.example.test/return");payments=new ShopPaymentService(env,orders,audit,new ObjectMapper());order=StoreOrder.builder().id(1L).paymentMethod("MOMO").total(100000d).status(OrderStatus.PENDING_PAYMENT).gatewayReference("GYM1").build();when(orders.findByGatewayReference("GYM1")).thenReturn(Optional.of(order));when(orders.findLocked(1L)).thenReturn(Optional.of(order));}
 Map<String,Object> callback(long amount){Map<String,Object> b=new HashMap<>();b.put("amount",amount);b.put("orderId","GYM1");b.put("partnerCode","test-partner");b.put("resultCode",0);b.put("transId","txn1");StringBuilder raw=new StringBuilder("accessKey=test-access");for(String k:List.of("amount","extraData","message","orderId","orderInfo","orderType","partnerCode","payType","requestId","responseTime","resultCode","transId"))raw.append("&").append(k).append("=").append(b.getOrDefault(k,""));b.put("signature",ShopPaymentService.hmac("test-secret",raw.toString()));return b;}
 @Test void forgedSignatureRejected(){var b=callback(100000);b.put("amount",1);assertThrows(IllegalArgumentException.class,()->payments.momo(b));verify(orders,never()).save(any());}
 @Test void wrongAmountRejected(){assertThrows(IllegalArgumentException.class,()->payments.momo(callback(90000)));assertNull(order.getPaidAt());}
 @Test void signedCallbackIsIdempotent(){payments.momo(callback(100000));assertEquals(OrderStatus.PAID,order.getStatus());assertNotNull(order.getPaidAt());payments.momo(callback(100000));verify(orders,times(1)).save(order);}
 @Test void latePaymentDoesNotReviveCancelledOrder(){order.setStatus(OrderStatus.CANCELLED);payments.momo(callback(100000));assertEquals(OrderStatus.CANCELLED,order.getStatus());assertNull(order.getPaidAt());verify(audit).event(eq(order),eq(OrderStatus.CANCELLED),contains("đối soát"));}
}
