package com.example.gymmanagement.shop;
import org.junit.jupiter.api.*; import static org.junit.jupiter.api.Assertions.*; import static org.mockito.Mockito.*; import org.springframework.beans.factory.annotation.Autowired; import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest; import org.springframework.context.annotation.Import; import org.springframework.test.context.bean.override.mockito.MockitoBean; import com.example.gymmanagement.entity.User; import com.example.gymmanagement.repository.UserRepository; import com.example.gymmanagement.service.*; import com.fasterxml.jackson.databind.ObjectMapper; import org.springframework.jdbc.core.JdbcTemplate; import jakarta.persistence.EntityManager; import java.util.*; import java.time.*;
@org.springframework.boot.test.autoconfigure.jdbc.AutoConfigureTestDatabase(replace=org.springframework.boot.test.autoconfigure.jdbc.AutoConfigureTestDatabase.Replace.NONE)
@DataJpaTest(properties={"spring.datasource.url=jdbc:h2:mem:shopupgrade;DB_CLOSE_DELAY=-1;NON_KEYWORDS=VALUE","spring.jpa.hibernate.ddl-auto=create-drop","spring.sql.init.mode=never"})
@Import({ShopService.class,ShopAuditService.class,ShopPaymentService.class,ShopCustomerService.class,ProductReviewService.class,ProductVariantService.class,ObjectMapper.class})
class ShopUpgradeTest {
 @Autowired ShopService shop; @Autowired ShopCustomerService customer; @Autowired ProductReviewService reviews; @Autowired ProductVariantService variantService; @Autowired ShopPaymentService payments; @Autowired UserRepository users; @Autowired ProductRepository products; @Autowired ProductVariantRepository variants; @Autowired StoreOrderRepository orders; @Autowired ShopInventoryMovementRepository movements; @Autowired CustomerProductStateRepository states; @Autowired CustomerAddressRepository addresses; @Autowired JdbcTemplate jdbc; @Autowired EntityManager em;
 @MockitoBean MembershipService memberships; @MockitoBean BankQrService qr; @MockitoBean NotificationService notifications; @MockitoBean VoucherService vouchers;
 User user; Product product;
 @BeforeEach void setup(){user=users.save(User.builder().email("buyer@example.test").fullName("Buyer").build());product=products.save(Product.builder().name("Áo tập").category(ProductCategory.EQUIPMENT).price(100000d).stock(10).build());}
 Map<String,Object> request(){return new HashMap<>(Map.of("receiverName","Người nhận","phone","0901234567","shippingAddress","12 Đường A","paymentMethod","COD"));}
 @Test void schemaHasExactly43BusinessTables(){assertEquals(43,jdbc.queryForObject("select count(*) from information_schema.tables where table_schema='PUBLIC' and table_type='BASE TABLE'",Integer.class));}
 @Test void codDoesNotExpireAndCancellationRestoresStockOnlyOnce(){shop.addCart(user.getEmail(),product.getId(),null,2);var result=shop.checkout(user.getEmail(),request());Long id=(Long)result.get("id");assertEquals(OrderStatus.CONFIRMED,result.get("status"));assertNull(result.get("expiresAt"));assertEquals(8,products.findById(product.getId()).orElseThrow().getStock());shop.expire();assertEquals(OrderStatus.CONFIRMED,orders.findById(id).orElseThrow().getStatus());shop.cancel(user.getEmail(),id);assertEquals(10,products.findById(product.getId()).orElseThrow().getStock());assertThrows(RuntimeException.class,()->shop.cancel(user.getEmail(),id));assertEquals(2,movements.count());}
 @Test void codRecordsPaymentOnDeliveryAndHistory(){shop.addCart(user.getEmail(),product.getId(),null,1);Long id=(Long)shop.checkout(user.getEmail(),request()).get("id");shop.updateStatus(id,OrderStatus.PREPARING);shop.updateStatus(id,OrderStatus.SHIPPING);assertNull(orders.findById(id).orElseThrow().getPaidAt());var result=shop.updateStatus(id,OrderStatus.DELIVERED);assertNotNull(result.get("paidAt"));assertEquals(4,((List<?>)result.get("history")).size());}
 @Test void addressOwnershipAndDefault(){var a=new CustomerAddress();a.setReceiverName("Buyer");a.setPhone("0901234567");a.setAddress("Địa chỉ 1");var first=customer.saveAddress(user.getEmail(),null,a);assertTrue(first.isDefaultAddress());var other=users.save(User.builder().email("other@example.test").fullName("Other").build());assertThrows(IllegalArgumentException.class,()->customer.saveAddress(other.getEmail(),first.getId(),a));a.setAddress("Địa chỉ 2");a.setDefaultAddress(true);var second=customer.saveAddress(user.getEmail(),null,a);assertFalse(first.isDefaultAddress());customer.deleteAddress(user.getEmail(),second.getId());assertTrue(customer.addresses(user.getEmail()).get(0).isDefaultAddress());}
 @Test void wishlistAndRecentShareOneRowAndDoNotCrossUsers(){customer.setState(user.getEmail(),product.getId(),true,false);customer.setState(user.getEmail(),product.getId(),null,true);assertEquals(1,states.count());assertEquals(1,((List<?>)customer.state(user.getEmail()).get("wishlist")).size());assertEquals(1,((List<?>)customer.state(user.getEmail()).get("recent")).size());var other=users.save(User.builder().email("other@example.test").build());assertTrue(((List<?>)customer.state(other.getEmail()).get("wishlist")).isEmpty());}
 @Test void reviewImagesRoundTripWithoutImageTable(){var o=orders.save(StoreOrder.builder().user(user).status(OrderStatus.DELIVERED).build());o.getItems().add(OrderItem.builder().order(o).productId(product.getId()).productName(product.getName()).quantity(1).build());orders.saveAndFlush(o);reviews.create(user.getEmail(),o.getId(),product.getId(),5,"Tốt",List.of("https://example.test/a.png"));em.flush();em.clear();assertEquals(List.of("https://example.test/a.png"),reviews.forProduct(product.getId()).get(0).get("images"));assertThrows(RuntimeException.class,()->reviews.create(user.getEmail(),o.getId(),product.getId(),5,"Trùng",List.of()));}
 @Test void variantAdjustmentAndCheckoutUseVariantStock(){var v=variants.save(ProductVariant.builder().product(product).stock(3).priceOverride(120000d).build());variantService.update(v.getId(),Map.of("stock",5));shop.addCart(user.getEmail(),product.getId(),v.getId(),2);var result=shop.checkout(user.getEmail(),request());assertEquals(240000d,result.get("subtotal"));assertEquals(3,v.getStock());assertEquals(10,product.getStock());assertEquals(2,movements.count());}
 @Test void unconfiguredGatewaysCannotCreateOrder(){shop.addCart(user.getEmail(),product.getId(),null,1);var req=request();req.put("paymentMethod","MOMO");assertFalse(payments.methods().get("MOMO"));assertThrows(IllegalArgumentException.class,()->shop.checkout(user.getEmail(),req));assertEquals(0,orders.count());assertEquals(10,product.getStock());}
 @Test void paginationClampsAndPreservesTotal(){var result=ShopExperienceController.page(List.of(1,2,3),1,2);assertEquals(List.of(3),result.get("items"));assertEquals(3,result.get("total"));assertEquals(List.of(),ShopExperienceController.page(List.of(1),Integer.MAX_VALUE,48).get("items"));}
}
