<template>
  <main class="home-page">
    <nav><div class="brand">GYM<span>PRO</span></div><div><router-link to="/login">Đăng nhập</router-link><router-link class="join" to="/register">Đăng ký</router-link></div></nav>
    <section class="hero">
      <div><p class="eyebrow">LUYỆN TẬP THÔNG MINH · TIẾN BỘ BỀN VỮNG</p><h1>Quản lý hành trình<br><span>tập luyện của bạn</span></h1><p class="lead">Giáo án cá nhân hóa, theo dõi từng buổi tập, dinh dưỡng và tiến độ — tất cả trong một nơi.</p><div class="actions"><router-link class="primary" to="/register">Bắt đầu ngay</router-link><router-link class="secondary" to="/login">Tôi đã có tài khoản</router-link></div></div>
      <div class="info-card"><div class="icon"></div><h2>GYMPRO</h2><p>Hệ thống quản lý phòng gym và trợ lý luyện tập cá nhân.</p><div class="metrics"><div><b>AI</b><span>Giáo án</span></div><div><b>24/7</b><span>Theo dõi</span></div><div><b>100%</b><span>Cá nhân hóa</span></div></div></div>
    </section>
    <section class="features"><article><b>01</b><h3>Giáo án phù hợp</h3><p>Tạo lịch tập theo mục tiêu, thể lực và số ngày bạn có thể luyện tập.</p></article><article><b>02</b><h3>Ghi nhận mỗi buổi</h3><p>Ghi nhận kết quả, khối lượng và theo dõi tiến bộ theo từng tuần.</p></article><article><b>03</b><h3>Bài tập & dinh dưỡng</h3><p>Tra cứu hướng dẫn bài tập và gợi ý món ăn phù hợp với mục tiêu.</p></article></section>
    <section class="demo-section"><h2>Hai hồ sơ — hai hướng giáo án khác nhau</h2><p>Dùng hai tài khoản dưới đây để xem thuật toán thay đổi lịch, bài tập và cường độ theo dữ liệu đầu vào.</p><div class="demo-grid"><article><b>VIP · TĂNG CƠ</b><h3>fulltest@gym.com</h3><p>Nam · 175 cm · 72 kg · trung bình · phòng gym · 4 buổi/tuần</p><code>password</code></article><article><b>FREE · GIẢM CÂN</b><h3>fulltest2@gym.com</h3><p>Nữ · 160 cm · 68 kg · mới tập · tại nhà · đau đầu gối · 3 buổi/tuần</p><code>password</code></article></div></section>
  </main>
</template>
<style scoped>
.home-page{min-height:100vh;background:linear-gradient(135deg,#f8fafc,#eef2f7);color:#1e293b;padding:0 7vw}nav{height:84px;display:flex;align-items:center;justify-content:space-between;border-bottom:1px solid #cbd5e1}.brand{font-size:1.7rem;font-weight:800;letter-spacing:.08em}.brand span,.eyebrow,h1 span{color:#f97316}nav a{color:#475569;text-decoration:none;margin-left:22px}.join,.primary{background:#172033!important;color:#fff!important;padding:12px 22px;border-radius:7px}.hero{min-height:570px;display:grid;grid-template-columns:1.25fr .75fr;gap:8vw;align-items:center}.eyebrow{font-weight:700;letter-spacing:.13em;font-size:.8rem}h1{font-size:clamp(3rem,6vw,5.8rem);line-height:.94;margin:20px 0}.lead{font-size:1.15rem;line-height:1.7;max-width:610px;color:#475569}.actions{display:flex;gap:14px;margin-top:34px}.actions a{text-decoration:none;padding:14px 24px;border-radius:7px}.secondary{border:1px solid #64748b;color:#172033}.info-card{background:#fff;padding:42px;border-radius:20px;box-shadow:0 18px 60px #0f172a1f}.icon{font-size:4rem}.info-card h2{font-size:2rem;margin:12px 0}.info-card p{color:#64748b;line-height:1.6}.metrics{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin-top:30px;border-top:1px solid #e2e8f0;padding-top:22px}.metrics div{display:flex;flex-direction:column}.metrics b{font-size:1.25rem;color:#f97316}.metrics span{font-size:.75rem;color:#64748b}.features{display:grid;grid-template-columns:repeat(3,1fr);gap:20px;padding:25px 0 45px}.features article,.demo-grid article{background:#ffffffd9;padding:26px;border:1px solid #e2e8f0;border-radius:12px}.features b,.demo-grid b{color:#f97316}.features h3,.demo-grid h3{margin:10px 0}.features p,.demo-section p{color:#64748b;line-height:1.55}.demo-section{padding:15px 0 70px}.demo-section>h2{text-align:center;font-size:2rem}.demo-section>p{text-align:center}.demo-grid{display:grid;grid-template-columns:1fr 1fr;gap:20px;margin-top:24px}.demo-grid code{background:#172033;color:#fff;padding:5px 9px;border-radius:6px}@media(max-width:800px){.hero,.demo-grid{grid-template-columns:1fr}.hero{padding:60px 0}.features{grid-template-columns:1fr}.info-card{display:none}nav{height:70px}.home-page{padding:0 5vw}}
</style>
