<template>
  <main class="home-page">
    <nav><div class="brand">GYM<span>PRO</span></div><div><router-link to="/login">Đăng nhập</router-link><router-link class="join" to="/register">Đăng ký</router-link></div></nav>
    <section class="hero">
      <div><p class="eyebrow">LUYỆN TẬP THÔNG MINH · TIẾN BỘ BỀN VỮNG</p><h1>Quản lý hành trình<br><span>tập luyện của bạn</span></h1><p class="lead">Giáo án cá nhân hóa, theo dõi từng buổi tập, dinh dưỡng và tiến độ — tất cả trong một nơi.</p><div class="actions"><router-link class="primary" to="/register">Bắt đầu ngay</router-link><router-link class="secondary" to="/login">Tôi đã có tài khoản</router-link></div></div>
      <div class="info-card"><div class="icon">🏋️</div><h2>GYMPRO</h2><p>Hệ thống quản lý phòng gym và trợ lý luyện tập cá nhân.</p><div class="metrics"><div><b>AI</b><span>Giáo án</span></div><div><b>24/7</b><span>Theo dõi</span></div><div><b>100%</b><span>Cá nhân hóa</span></div></div></div>
    </section>
    <section class="features"><article><b>01</b><h3>Giáo án phù hợp</h3><p>Tạo lịch tập theo mục tiêu, thể lực và số ngày bạn có thể luyện tập.</p></article><article><b>02</b><h3>Ghi nhận mỗi buổi</h3><p>Checkout kết quả, khối lượng và theo dõi tiến bộ theo từng tuần.</p></article><article><b>03</b><h3>Bài tập & dinh dưỡng</h3><p>Tra cứu hướng dẫn bài tập và gợi ý món ăn phù hợp với mục tiêu.</p></article></section>
  </main>
</template>
<style scoped>
.home-page{min-height:100vh;background:linear-gradient(135deg,#fffaf5,#f2dfca);color:#25140b;padding:0 7vw}nav{height:84px;display:flex;align-items:center;justify-content:space-between;border-bottom:1px solid #d8b995}.brand{font-size:1.7rem;font-weight:800;letter-spacing:.08em}.brand span,.eyebrow,h1 span{color:#b8651a}nav a{color:#4a3728;text-decoration:none;margin-left:22px}.join,.primary{background:#6b4226!important;color:#fff!important;padding:12px 22px;border-radius:7px}.hero{min-height:570px;display:grid;grid-template-columns:1.25fr .75fr;gap:8vw;align-items:center}.eyebrow{font-weight:700;letter-spacing:.13em;font-size:.8rem}h1{font-size:clamp(3rem,6vw,5.8rem);line-height:.94;margin:20px 0}.lead{font-size:1.15rem;line-height:1.7;max-width:610px;color:#654d3d}.actions{display:flex;gap:14px;margin-top:34px}.actions a{text-decoration:none;padding:14px 24px;border-radius:7px}.secondary{border:1px solid #8c5c3e;color:#4a2810}.info-card{background:#fff;padding:42px;border-radius:20px;box-shadow:0 18px 60px #6b422629}.icon{font-size:4rem}.info-card h2{font-size:2rem;margin:12px 0}.info-card p{color:#765c49;line-height:1.6}.metrics{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin-top:30px;border-top:1px solid #ead9c8;padding-top:22px}.metrics div{display:flex;flex-direction:column}.metrics b{font-size:1.25rem;color:#b8651a}.metrics span{font-size:.75rem;color:#8c7060}.features{display:grid;grid-template-columns:repeat(3,1fr);gap:20px;padding:25px 0 70px}.features article{background:#ffffffa8;padding:26px;border:1px solid #e0c6ab;border-radius:12px}.features b{color:#d4892a}.features h3{margin:10px 0}.features p{color:#765c49;line-height:1.55}@media(max-width:800px){.hero{grid-template-columns:1fr;padding:60px 0}.features{grid-template-columns:1fr}.info-card{display:none}nav{height:70px}.home-page{padding:0 5vw}}
</style>
