<template><main class="detail" v-loading="loading"><router-link :to="auth.isLoggedIn?'/app/shop':'/shop'">← Cửa hàng</router-link><el-alert v-if="error" :title="error" type="error" :closable="false"/>
 <template v-if="product"><div class="hero"><div><el-image class="cover" :src="gallery[0]||fallback" :preview-src-list="gallery" fit="cover"/><div class="gallery"><el-image v-for="url in gallery" :key="url" :src="url" :preview-src-list="gallery" fit="cover"/></div></div><div><h1>{{product.name}}</h1><p>{{product.brand}}</p><h2>{{product.hasVariants?'Từ ':''}}{{money(product.displayPrice)}}</h2><p>★ {{product.averageRating||'Chưa có'}} · {{product.reviewCount}} đánh giá · Còn {{product.stock}}</p><p class="description">{{product.description}}</p><el-button type="primary" :disabled="product.stock<=0" @click="add">{{product.hasVariants?'Chọn phân loại':'Thêm vào giỏ'}}</el-button><el-button @click="toggle(product)">{{wishlist.some(p=>p.id===product.id)?'♥ Đã yêu thích':'♡ Yêu thích'}}</el-button><el-button @click="router.push(auth.isLoggedIn?'/app/shop?tab=cart':'/shop')">Xem giỏ</el-button></div></div>
 <h2>Đánh giá từ người đã mua</h2><el-select v-model="rating" clearable placeholder="Tất cả số sao" @change="page=1;loadReviews()"><el-option v-for="n in 5" :key="n" :value="n" :label="n+' sao'"/></el-select>
 <el-empty v-if="!reviews.length" description="Chưa có đánh giá phù hợp"/><article v-for="r in reviews" :key="r.id" class="review"><b>{{r.userName}}</b><el-rate :model-value="r.rating" disabled/><small>{{new Date(r.createdAt).toLocaleDateString('vi-VN')}}</small><p>{{r.comment}}</p><div class="gallery"><el-image v-for="url in r.images" :key="url" :src="url" :preview-src-list="r.images" fit="cover"/></div></article><el-pagination v-model:current-page="page" :total="total" :page-size="6" layout="prev,pager,next" @current-change="loadReviews"/><p>Để viết đánh giá, mở đơn đã nhận trong mục Đơn hàng.</p>
 <h2>Sản phẩm liên quan</h2><div class="related"><router-link v-for="p in product.related" :key="p.id" :to="'/shop/product/'+p.id"><img :src="p.imageUrl||p.images?.[0]" :alt="p.name"/><b>{{p.name}}</b><p>{{money(p.displayPrice)}}</p></router-link></div></template><ProductVariantPicker ref="picker" :add-item="addSelected"/></main></template>
<script setup>
import {ref,computed,watch} from 'vue';import {useRoute,useRouter} from 'vue-router';import {shopAPI} from '@/api';import {useAuthStore} from '@/stores/auth';import {useShopCustomer} from '@/composables/useShopCustomer';import {ElMessage} from 'element-plus';import ProductVariantPicker from '@/components/shop/ProductVariantPicker.vue'
const route=useRoute(),router=useRouter(),auth=useAuthStore(),{wishlist,refresh,toggle,viewed,guestCart,persistCart}=useShopCustomer(),product=ref(null),reviews=ref([]),page=ref(1),total=ref(0),rating=ref(null),loading=ref(false),error=ref(''),picker=ref(null)
const fallback='https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800';const money=v=>Number(v||0).toLocaleString('vi-VN')+' đ',gallery=computed(()=>[...new Set([product.value?.imageUrl,...(product.value?.images||[])].filter(Boolean))])
let request=0
async function load(){const id=++request;loading.value=true;product.value=null;error.value='';page.value=1;rating.value=null;try{const r=await shopAPI.detail(route.params.id);if(id!==request)return;product.value=r.data;await loadReviews();await refresh();await viewed(r.data)}catch{error.value='Không tải được sản phẩm hoặc sản phẩm đã ngừng bán.'}finally{if(id===request)loading.value=false}}
async function loadReviews(){const id=route.params.id;const r=await shopAPI.productReviews(id,{page:page.value-1,size:6,rating:rating.value||undefined});if(id===route.params.id){reviews.value=r.data.items;total.value=r.data.total}}
async function add(){if(product.value.hasVariants)picker.value.open(product.value);else await addSelected(product.value)}
async function addSelected(p,v=null){if(auth.isLoggedIn)await shopAPI.addCart(p.id,1,v?.id??null);else{const vid=v?.id??null,stock=v?.stock??p.stock,existing=guestCart.value.find(i=>i.id===p.id&&(i.variantId??null)===vid);if((existing?.quantity||0)+1>stock){ElMessage.warning('Số lượng đã đạt tồn kho');return false}const item={...p,variantId:vid,variantLabel:v?.label??null,stock,unitPrice:v?.priceOverride>0?v.priceOverride:p.salePrice||p.price,quantity:(existing?.quantity||0)+1};if(existing)Object.assign(existing,item);else guestCart.value.push(item);persistCart()}ElMessage.success('Đã thêm vào giỏ')}
watch(()=>route.params.id,load,{immediate:true})
</script><style scoped>.detail{max-width:1100px;margin:24px auto;padding:20px}.hero{display:grid;grid-template-columns:1fr 1fr;gap:36px;margin:24px 0}.cover{width:100%;height:350px;border-radius:12px}.gallery{display:flex;gap:10px;flex-wrap:wrap;margin-top:12px}.gallery .el-image{width:85px;height:85px;border-radius:6px}.description{white-space:pre-wrap;line-height:1.7}.review{padding:18px 0;border-bottom:1px solid var(--el-border-color)}.related{display:grid;grid-template-columns:repeat(auto-fit,minmax(170px,1fr));gap:20px}.related a{color:inherit;text-decoration:none}.related img{width:100%;height:150px;object-fit:cover;display:block}@media(max-width:700px){.hero{grid-template-columns:1fr}.cover{height:260px}}</style>