<template><main class="public-shop">
<header><router-link to="/">GYMPRO</router-link><router-link to="/tra-cuu-don">Tra cứu đơn</router-link><router-link v-if="auth.isLoggedIn" to="/app/shop">Đơn hàng của tôi</router-link><el-button type="primary" @click="openCart">Giỏ hàng ({{count}})</el-button></header>
<div v-if="vouchers.length" class="promo">Khuyến mãi: <el-tag v-for="v in vouchers" :key="v.code">{{v.code}} — {{v.type==='PERCENT'?v.value+'%':money(v.value)}}</el-tag></div>
<ShopCatalog @add="add"/>
<ProductVariantPicker ref="picker" :add-item="addSelected"/>
<el-drawer v-model="cartOpen" title="Giỏ hàng của bạn" size="min(560px, 100vw)">
 <el-empty v-if="!guestCart.length" description="Giỏ hàng đang trống"/>
 <div v-for="(i,index) in guestCart" :key="i.id+':'+i.variantId" class="cart-row"><router-link :to="'/shop/product/'+i.id">{{i.name}}</router-link><p>{{i.variantLabel}}</p><b>{{money(i.unitPrice??i.salePrice??i.price)}}</b><el-input-number v-model="i.quantity" :min="1" :max="Math.max(1,i.stock||0)" :disabled="i.stock<=0" @change="persistCart"/><el-button text type="danger" @click="guestCart.splice(index,1);persistCart()">Xóa</el-button><small v-if="i.stock<=0">Hết hàng, vui lòng xóa khỏi giỏ.</small></div>
 <template #footer><p>Tạm tính: <b>{{money(total)}}</b></p><small>Giá và tồn kho được kiểm tra lại khi đặt hàng.</small><el-button type="primary" :disabled="!guestCart.length" @click="router.push('/login')">Đăng nhập để thanh toán</el-button></template>
</el-drawer>
</main></template>
<script setup>
import {ref,computed,onMounted} from 'vue';import {useRouter} from 'vue-router';import {shopAPI} from '@/api';import {useAuthStore} from '@/stores/auth';import {useShopCustomer} from '@/composables/useShopCustomer';import {ElMessage} from 'element-plus';import ShopCatalog from '@/components/shop/ShopCatalog.vue';import ProductVariantPicker from '@/components/shop/ProductVariantPicker.vue'
const router=useRouter(),auth=useAuthStore(),{guestCart,persistCart}=useShopCustomer(),picker=ref(null),cartOpen=ref(false),serverCount=ref(0),vouchers=ref([])
const money=v=>Number(v||0).toLocaleString('vi-VN')+' đ',count=computed(()=>auth.isLoggedIn?serverCount.value:guestCart.value.reduce((s,i)=>s+i.quantity,0)),total=computed(()=>guestCart.value.reduce((s,i)=>s+(i.unitPrice??i.salePrice??i.price)*i.quantity,0))
async function refreshCount(){if(auth.isLoggedIn)serverCount.value=((await shopAPI.cart()).data||[]).reduce((s,i)=>s+i.quantity,0)}
async function openCart(){if(auth.isLoggedIn){router.push('/app/shop?tab=cart');return}cartOpen.value=true}
async function add(p){try{const current=(await shopAPI.detail(p.id)).data;if(current.hasVariants)picker.value.open(current);else await addSelected(current)}catch{}}
async function addSelected(p,v=null){if(auth.isLoggedIn){await shopAPI.addCart(p.id,1,v?.id??null);await refreshCount()}else{const stock=v?.stock??p.stock,id=v?.id??null,existing=guestCart.value.find(i=>i.id===p.id&&(i.variantId??null)===id);if((existing?.quantity||0)+1>stock){ElMessage.warning('Số lượng đã đạt tồn kho');return false}const data={...p,variantId:id,variantLabel:v?.label??null,stock,unitPrice:v?.priceOverride>0?v.priceOverride:p.salePrice||p.price,quantity:(existing?.quantity||0)+1};if(existing)Object.assign(existing,data);else guestCart.value.push(data);persistCart()}ElMessage.success('Đã thêm vào giỏ')}
onMounted(async()=>{vouchers.value=(await shopAPI.publicVouchers()).data||[];await refreshCount()})
</script><style scoped>.public-shop{max-width:1280px;margin:auto;padding:20px}header{display:flex;gap:18px;align-items:center;flex-wrap:wrap;margin-bottom:20px}header>a:first-child{font-weight:900;margin-right:auto}a{color:inherit}.promo{padding:12px;background:var(--el-color-warning-light-9)}.promo .el-tag{margin:4px}.cart-row{padding:16px 0;border-bottom:1px solid var(--el-border-color)}.cart-row p{margin:6px 0}.cart-row .el-input-number{margin:10px}.cart-row small{display:block;color:var(--el-color-danger)}</style>