package com.example.gymmanagement.shop;
import com.example.gymmanagement.dto.response.ApiResponse; import lombok.RequiredArgsConstructor; import org.springframework.web.bind.annotation.*; import org.springframework.security.core.annotation.AuthenticationPrincipal; import org.springframework.security.core.userdetails.UserDetails; import org.springframework.security.access.prepost.PreAuthorize; import org.springframework.transaction.annotation.Transactional; import org.springframework.data.domain.*; import java.util.*; import java.time.*;
@RestController @RequestMapping("/api/shop") @RequiredArgsConstructor @Transactional public class ShopExperienceController {
 private final com.example.gymmanagement.service.FileStorageService files; private final ShopCustomerService customers; private final ShopService shop; private final ProductRepository products; private final ProductVariantRepository variants; private final ShopInventoryMovementRepository movements; private final StoreOrderRepository orders;
 @PostMapping("/images") public Object image(@RequestParam("file")org.springframework.web.multipart.MultipartFile file){if(file.getSize()>5*1024*1024||!Set.of("image/jpeg","image/png","image/webp").contains(file.getContentType())||file.getOriginalFilename()==null||!file.getOriginalFilename().toLowerCase().matches(".*\\.(jpg|jpeg|png|webp)$"))throw new IllegalArgumentException("Chọn ảnh JPG, PNG hoặc WebP tối đa 5 MB");return ApiResponse.success(files.store(file,"shop").getUrl());}
 @GetMapping("/catalog") public Object catalog(@AuthenticationPrincipal UserDetails u,@RequestParam(required=false)String category,@RequestParam(required=false)String keyword,@RequestParam(defaultValue="0")double minPrice,@RequestParam(required=false)Double maxPrice,@RequestParam(defaultValue="newest")String sort,@RequestParam(defaultValue="0")int page,@RequestParam(defaultValue="12")int size){var list=new ArrayList<>(shop.products(u==null?null:u.getUsername(),category,keyword).stream().filter(p->((Number)p.get("displayPrice")).doubleValue()>=minPrice&&(maxPrice==null||((Number)p.get("displayPrice")).doubleValue()<=maxPrice)).toList());Comparator<Map<String,Object>> comparator=switch(sort){case "priceAsc"->Comparator.comparingDouble(p->((Number)p.get("displayPrice")).doubleValue());case "priceDesc"->Comparator.<Map<String,Object>>comparingDouble(p->((Number)p.get("displayPrice")).doubleValue()).reversed();case "rating"->Comparator.<Map<String,Object>>comparingDouble(p->p.get("averageRating")==null?0:((Number)p.get("averageRating")).doubleValue()).reversed();default->Comparator.<Map<String,Object>>comparingLong(p->((Number)p.get("id")).longValue()).reversed();};list.sort(comparator);return ApiResponse.success(page(list,page,size));}
 public static <T> Map<String,Object> page(List<T> list,int page,int size){size=Math.max(1,Math.min(48,size));page=Math.max(0,page);int from=(int)Math.min((long)page*size,list.size());return Map.of("items",list.subList(from,Math.min(from+size,list.size())),"total",list.size(),"page",page,"size",size);}
 @GetMapping("/products/{id}") public Object detail(@PathVariable Long id){var p=products.findById(id).filter(x->Boolean.TRUE.equals(x.getActive())).orElseThrow();var result=shop.productMap(p,null);result.put("related",shop.products(null,p.getCategory().name(),null).stream().filter(x->!id.equals(x.get("id"))).limit(4).toList());return ApiResponse.success(result);}
 @GetMapping("/addresses") public Object addresses(@AuthenticationPrincipal UserDetails u){return ApiResponse.success(customers.addresses(u.getUsername()));}
 @PostMapping("/addresses") public Object create(@AuthenticationPrincipal UserDetails u,@RequestBody CustomerAddress a){return ApiResponse.success(customers.saveAddress(u.getUsername(),null,a));}
 @PutMapping("/addresses/{id}") public Object update(@AuthenticationPrincipal UserDetails u,@PathVariable Long id,@RequestBody CustomerAddress a){return ApiResponse.success(customers.saveAddress(u.getUsername(),id,a));}
 @DeleteMapping("/addresses/{id}") public Object delete(@AuthenticationPrincipal UserDetails u,@PathVariable Long id){customers.deleteAddress(u.getUsername(),id);return ApiResponse.success("Đã xóa");}
 @GetMapping("/customer-state") public Object state(@AuthenticationPrincipal UserDetails u){return ApiResponse.success(customers.state(u.getUsername()));}
 @PutMapping("/customer-state/{id}") public Object state(@AuthenticationPrincipal UserDetails u,@PathVariable Long id,@RequestBody Map<String,Object> b){customers.setState(u.getUsername(),id,b.containsKey("wishlisted")?Boolean.valueOf(String.valueOf(b.get("wishlisted"))):null,Boolean.TRUE.equals(b.get("viewed")));return ApiResponse.success("Đã lưu");}
 @GetMapping("/admin/inventory") @PreAuthorize("hasAuthority('ROLE_ADMIN')") public Object inventory(@RequestParam(required=false)Long productId,@RequestParam(defaultValue="0")int page){var pageable=PageRequest.of(Math.max(0,page),20,Sort.by("id").descending());var result=productId==null?movements.findAll(pageable):movements.findByProductId(productId,pageable);return ApiResponse.success(Map.of("items",result.getContent(),"total",result.getTotalElements(),"lowStock",lowStock()));}
 private List<Map<String,Object>> lowStock(){List<Map<String,Object>> list=new ArrayList<>();for(Product p:products.findByActiveTrueOrderByCreatedAtDesc()){var pv=variants.findByProductIdOrderByIdAsc(p.getId());if(pv.isEmpty()&&p.getStock()<=5)list.add(Map.of("productId",p.getId(),"name",p.getName(),"sku","","stock",p.getStock()));for(var v:pv)if(Boolean.TRUE.equals(v.getActive())&&v.getStock()<=5)list.add(Map.of("productId",p.getId(),"name",p.getName(),"sku",v.getSku()==null?"#"+v.getId():v.getSku(),"stock",v.getStock()));}return list;}
 @GetMapping("/admin/statistics") @PreAuthorize("hasAuthority('ROLE_ADMIN')") public Object statistics(@RequestParam(required=false)LocalDate from,@RequestParam(required=false)LocalDate to){LocalDate start=from==null?LocalDate.now().withDayOfMonth(1):from,end=to==null?LocalDate.now():to;if(end.isBefore(start))throw new IllegalArgumentException("Khoảng ngày không hợp lệ");var selected=orders.findAllByOrderByCreatedAtDesc().stream().filter(o->o.getCreatedAt()!=null&&!o.getCreatedAt().toLocalDate().isBefore(start)&&!o.getCreatedAt().toLocalDate().isAfter(end)).toList();var paid=selected.stream().filter(o->o.getPaidAt()!=null&&o.getStatus()!=OrderStatus.CANCELLED&&o.getStatus()!=OrderStatus.EXPIRED).toList();Map<String,Double> daily=new TreeMap<>();Map<Long,Map<String,Object>> top=new HashMap<>();for(var o:paid){daily.merge(o.getCreatedAt().toLocalDate().toString(),o.getTotal(),Double::sum);for(var i:o.getItems()){var row=top.computeIfAbsent(i.getProductId(),id->new HashMap<>(Map.of("productId",id,"name",i.getProductName(),"quantity",0,"grossSales",0d)));row.put("quantity",(Integer)row.get("quantity")+i.getQuantity());row.put("grossSales",(Double)row.get("grossSales")+i.getLineTotal());}}return ApiResponse.success(Map.of("orderCount",selected.size(),"paidCount",paid.size(),"revenue",paid.stream().mapToDouble(StoreOrder::getTotal).sum(),"onlineRevenue",paid.stream().filter(o->o.getChannel()==SalesChannel.ONLINE).mapToDouble(StoreOrder::getTotal).sum(),"posRevenue",paid.stream().filter(o->o.getChannel()==SalesChannel.POS).mapToDouble(StoreOrder::getTotal).sum(),"daily",daily,"topProducts",top.values().stream().sorted(Comparator.<Map<String,Object>>comparingInt(p->(Integer)p.get("quantity")).reversed()).limit(10).toList(),"lowStock",lowStock()));}
}
