package com.example.gymmanagement.shop;
import lombok.RequiredArgsConstructor; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import com.example.gymmanagement.repository.UserRepository; import java.util.*; import java.time.*;
@Service @RequiredArgsConstructor @Transactional public class ShopCustomerService {
 private final UserRepository users; private final CustomerAddressRepository addresses; private final CustomerProductStateRepository states; private final ProductRepository products; private final ShopService shop;
 private Long uid(String email){return users.findLockedByEmail(email).orElseThrow().getId();}
 public List<CustomerAddress> addresses(String email){return addresses.findByUserIdOrderByIdAsc(uid(email));}
 public CustomerAddress saveAddress(String email,Long id,CustomerAddress input){Long uid=uid(email);var list=addresses.findByUserIdOrderByIdAsc(uid);var a=id==null?new CustomerAddress():list.stream().filter(x->x.getId().equals(id)).findFirst().orElseThrow(()->new IllegalArgumentException("Không có quyền truy cập địa chỉ"));if(input.getReceiverName()==null||input.getReceiverName().isBlank()||input.getPhone()==null||!input.getPhone().matches("[+0-9 ()-]{8,20}")||input.getAddress()==null||input.getAddress().isBlank()||input.getAddress().length()>1000)throw new IllegalArgumentException("Thông tin nhận hàng không hợp lệ");if(id==null&&list.size()>=20)throw new IllegalArgumentException("Tối đa 20 địa chỉ");a.setUserId(uid);a.setReceiverName(input.getReceiverName().trim());a.setPhone(input.getPhone().trim());a.setAddress(input.getAddress().trim());boolean makeDefault=input.isDefaultAddress()||list.isEmpty()||a.isDefaultAddress();if(makeDefault){list.forEach(x->x.setDefaultAddress(false));addresses.saveAll(list);}a.setDefaultAddress(makeDefault);return addresses.save(a);}
 public void deleteAddress(String email,Long id){var a=addresses.findById(id).orElseThrow();if(!a.getUserId().equals(uid(email)))throw new IllegalArgumentException("Không có quyền");boolean wasDefault=a.isDefaultAddress();addresses.delete(a);addresses.flush();if(wasDefault){var remaining=addresses(email);if(!remaining.isEmpty()){remaining.get(0).setDefaultAddress(true);addresses.save(remaining.get(0));}}}
 public Map<String,Object> state(String email){var list=states.findByUserIdOrderByViewedAtDesc(uid(email));return Map.of("wishlist",mapProducts(list.stream().filter(CustomerProductState::isWishlisted).toList()),"recent",mapProducts(list.stream().filter(x->x.getViewedAt()!=null).limit(30).toList()));}
 private List<Map<String,Object>> mapProducts(List<CustomerProductState> list){return list.stream().map(x->products.findById(x.getProductId()).filter(p->Boolean.TRUE.equals(p.getActive())).map(p->shop.productMap(p,null)).orElse(null)).filter(Objects::nonNull).toList();}
 public void setState(String email,Long productId,Boolean wish,boolean viewed){Long uid=uid(email);products.findById(productId).filter(p->Boolean.TRUE.equals(p.getActive())).orElseThrow();var s=states.findByUserIdAndProductId(uid,productId).orElseGet(CustomerProductState::new);s.setUserId(uid);s.setProductId(productId);if(wish!=null)s.setWishlisted(wish);if(viewed)s.setViewedAt(LocalDateTime.now());states.save(s);var recent=states.findByUserIdOrderByViewedAtDesc(uid).stream().filter(x->x.getViewedAt()!=null).toList();for(int i=30;i<recent.size();i++){var old=recent.get(i);if(old.isWishlisted()){old.setViewedAt(null);states.save(old);}else states.delete(old);}}
}
