package com.example.gymmanagement.shop;
import lombok.RequiredArgsConstructor; import org.springframework.stereotype.Service; import org.springframework.core.env.Environment; import org.springframework.transaction.annotation.Transactional; import com.fasterxml.jackson.databind.ObjectMapper; import com.fasterxml.jackson.databind.JsonNode; import java.util.*; import java.time.*; import java.time.format.DateTimeFormatter; import java.net.*; import java.net.http.*; import java.nio.charset.StandardCharsets; import javax.crypto.Mac; import javax.crypto.spec.SecretKeySpec; import java.security.MessageDigest;
@Service @RequiredArgsConstructor public class ShopPaymentService {
 private final Environment env; private final StoreOrderRepository orders; private final ShopAuditService audit; private final ObjectMapper json;
 private String cfg(String key){return env.getProperty("shop.payment."+key,"");}
 private String cfg(String key,String fallback){return env.getProperty("shop.payment."+key,fallback);}
 public Map<String,Boolean> methods(){return Map.of("BANK_TRANSFER",true,"COD",true,"MOMO",available("MOMO"),"ZALOPAY",available("ZALOPAY"));}
 private boolean available(String method){if(!Set.of("MOMO","ZALOPAY").contains(method))return Set.of("COD","BANK_TRANSFER").contains(method);String prefix=method.toLowerCase();if(!"true".equals(cfg(prefix+".enabled"))||!cfg("backend-url").startsWith("https://")||!cfg("return-url").startsWith("https://"))return false;return (method.equals("MOMO")?List.of("partner-code","access-key","secret-key"):List.of("app-id","key1","key2")).stream().allMatch(k->!cfg(prefix+"."+k).isBlank());}
 public void requireAvailable(String method){if(!available(method))throw new IllegalArgumentException("Phương thức thanh toán chưa được cấu hình hoặc không hợp lệ");}
 public static String hmac(String key,String raw){try{Mac m=Mac.getInstance("HmacSHA256");m.init(new SecretKeySpec(key.getBytes(StandardCharsets.UTF_8),"HmacSHA256"));return HexFormat.of().formatHex(m.doFinal(raw.getBytes(StandardCharsets.UTF_8)));}catch(Exception e){throw new IllegalArgumentException("Không thể ký thanh toán",e);}}
 private boolean equal(String a,String b){return b!=null&&MessageDigest.isEqual(a.getBytes(StandardCharsets.UTF_8),b.getBytes(StandardCharsets.UTF_8));}
 private String enc(String s){return URLEncoder.encode(s,StandardCharsets.UTF_8);}
 @Transactional public Map<String,String> start(String email,Long id){StoreOrder o=orders.findLocked(id).orElseThrow();if(o.getUser()==null||!o.getUser().getEmail().equalsIgnoreCase(email))throw new IllegalArgumentException("Không có quyền");String method=o.getPaymentMethod();requireAvailable(method);if(!Set.of("MOMO","ZALOPAY").contains(method)||o.getStatus()!=OrderStatus.PENDING_PAYMENT||o.getExpiresAt()==null||o.getExpiresAt().isBefore(LocalDateTime.now()))throw new IllegalArgumentException("Đơn không thể thanh toán qua ví");if(o.getPaymentUrl()!=null&&!o.getPaymentUrl().isBlank())return Map.of("payUrl",o.getPaymentUrl());
 try{String ref=method.equals("MOMO")?"GYM"+id:LocalDate.now(ZoneId.of("Asia/Ho_Chi_Minh")).format(DateTimeFormatter.ofPattern("yyMMdd"))+"_GYM"+id;long amount=Math.round(o.getTotal());String callback=cfg("backend-url")+"/api/shop/payments/";JsonNode response;
 if(method.equals("MOMO")){Map<String,Object> req=new TreeMap<>();req.put("partnerCode",cfg("momo.partner-code"));req.put("requestId",ref);req.put("amount",amount);req.put("orderId",ref);req.put("orderInfo","Thanh toan GYM "+id);req.put("redirectUrl",cfg("return-url"));req.put("ipnUrl",callback+"momo/ipn");req.put("extraData","");req.put("requestType","captureWallet");String raw="accessKey="+cfg("momo.access-key")+"&amount="+amount+"&extraData=&ipnUrl="+req.get("ipnUrl")+"&orderId="+ref+"&orderInfo="+req.get("orderInfo")+"&partnerCode="+req.get("partnerCode")+"&redirectUrl="+req.get("redirectUrl")+"&requestId="+ref+"&requestType=captureWallet";req.put("signature",hmac(cfg("momo.secret-key"),raw));req.put("lang","vi");response=post(cfg("momo.endpoint","https://test-payment.momo.vn/v2/gateway/api/create"),json.writeValueAsString(req),"application/json");if(response.path("resultCode").asInt(-1)!=0)throw new IllegalArgumentException("MoMo chưa tạo được phiên thanh toán");}
 else{Map<String,String> req=new LinkedHashMap<>();req.put("app_id",cfg("zalopay.app-id"));req.put("app_trans_id",ref);req.put("app_user","gym_customer_"+o.getUser().getId());req.put("app_time",String.valueOf(System.currentTimeMillis()));req.put("amount",String.valueOf(amount));req.put("item","[]");req.put("embed_data",json.writeValueAsString(Map.of("redirecturl",cfg("return-url"))));req.put("description","Thanh toan GYM "+id);req.put("callback_url",callback+"zalopay/callback");req.put("expire_duration_seconds",String.valueOf(Math.max(1,Duration.between(LocalDateTime.now(),o.getExpiresAt()).getSeconds())));req.put("mac",hmac(cfg("zalopay.key1"),req.get("app_id")+"|"+ref+"|"+req.get("app_user")+"|"+amount+"|"+req.get("app_time")+"|"+req.get("embed_data")+"|[]"));response=post(cfg("zalopay.endpoint","https://sb-openapi.zalopay.vn/v2/create"),req.entrySet().stream().map(e->enc(e.getKey())+"="+enc(e.getValue())).reduce((a,c)->a+"&"+c).orElse(""),"application/x-www-form-urlencoded");if(response.path("return_code").asInt()!=1)throw new IllegalArgumentException("ZaloPay chưa tạo được phiên thanh toán");}
 String url=response.path(method.equals("MOMO")?"payUrl":"order_url").asText();if(!url.startsWith("https://"))throw new IllegalArgumentException("Cổng không trả URL thanh toán hợp lệ");o.setGatewayReference(ref);o.setPaymentUrl(url);orders.save(o);audit.event(o,o.getStatus(),"Tạo phiên thanh toán "+method);return Map.of("payUrl",url);
 }catch(IllegalArgumentException e){throw e;}catch(Exception e){throw new IllegalArgumentException("Không thể kết nối cổng thanh toán. Vui lòng thử lại.");}}
 private JsonNode post(String url,String body,String contentType)throws Exception{if(!url.startsWith("https://"))throw new IllegalArgumentException("Cổng cần HTTPS");var client=HttpClient.newBuilder().connectTimeout(Duration.ofSeconds(10)).build();var req=HttpRequest.newBuilder(URI.create(url)).timeout(Duration.ofSeconds(20)).header("Content-Type",contentType).POST(HttpRequest.BodyPublishers.ofString(body)).build();var r=client.send(req,HttpResponse.BodyHandlers.ofString());if(r.statusCode()/100!=2)throw new IllegalArgumentException("Cổng thanh toán chưa sẵn sàng");return json.readTree(r.body());}
 @Transactional public void momo(Map<String,Object> b){if(!available("MOMO"))throw new IllegalArgumentException("MoMo chưa cấu hình");StringBuilder raw=new StringBuilder("accessKey="+cfg("momo.access-key"));for(String key:List.of("amount","extraData","message","orderId","orderInfo","orderType","partnerCode","payType","requestId","responseTime","resultCode","transId"))raw.append("&").append(key).append("=").append(b.getOrDefault(key,""));if(!equal(hmac(cfg("momo.secret-key"),raw.toString()),String.valueOf(b.get("signature")))||!cfg("momo.partner-code").equals(String.valueOf(b.get("partnerCode"))))throw new IllegalArgumentException("Chữ ký không hợp lệ");if("0".equals(String.valueOf(b.get("resultCode"))))settle("MOMO",String.valueOf(b.get("orderId")),Long.parseLong(String.valueOf(b.get("amount"))),String.valueOf(b.get("transId")));}
 @Transactional public void zalo(Map<String,Object>b){if(!available("ZALOPAY"))throw new IllegalArgumentException("ZaloPay chưa cấu hình");String data=String.valueOf(b.get("data"));if(!equal(hmac(cfg("zalopay.key2"),data),String.valueOf(b.get("mac"))))throw new IllegalArgumentException("Chữ ký không hợp lệ");try{var d=json.readTree(data);if(!cfg("zalopay.app-id").equals(d.path("app_id").asText()))throw new IllegalArgumentException("Sai ứng dụng");settle("ZALOPAY",d.path("app_trans_id").asText(),d.path("amount").asLong(),d.path("zp_trans_id").asText());}catch(java.io.IOException e){throw new IllegalArgumentException("Callback không hợp lệ");}}
 private void settle(String method,String reference,long amount,String transaction){var found=orders.findByGatewayReference(reference).orElseThrow();var o=orders.findLocked(found.getId()).orElseThrow();if(!method.equals(o.getPaymentMethod())||amount!=Math.round(o.getTotal()))throw new IllegalArgumentException("Giao dịch không khớp");if(o.getPaidAt()!=null){if(!Objects.equals(o.getTransactionId(),transaction))throw new IllegalArgumentException("Giao dịch trùng khác mã");return;}if(o.getStatus()!=OrderStatus.PENDING_PAYMENT){audit.event(o,o.getStatus(),"Cần đối soát: "+method+" đã thu tiền sau khi đơn kết thúc. Mã "+transaction);return;}o.setStatus(OrderStatus.PAID);o.setPaidAt(LocalDateTime.now());o.setTransactionId(transaction);audit.event(o,OrderStatus.PENDING_PAYMENT,method+" xác nhận thanh toán");orders.save(o);}
}
