package com.example.gymmanagement.shop;
import com.example.gymmanagement.dto.response.ApiResponse; import lombok.RequiredArgsConstructor; import org.springframework.beans.factory.annotation.Value; import org.springframework.http.*; import org.springframework.security.access.prepost.PreAuthorize; import org.springframework.security.core.annotation.AuthenticationPrincipal; import org.springframework.security.core.userdetails.UserDetails; import org.springframework.web.bind.annotation.*; import java.util.*;
@RestController @RequestMapping("/api/shop") @RequiredArgsConstructor
public class ShopController { private final ShopService shop; private final VoucherService voucherService; private final ShopOtpService otp; private final com.example.gymmanagement.service.EmailService email; @Value("${shop.otp.enabled:false}") private boolean otpEnabled;
 @GetMapping("/products") public ResponseEntity<?> products(@AuthenticationPrincipal UserDetails u,@RequestParam(required=false)String category,@RequestParam(required=false)String keyword){return ResponseEntity.ok(ApiResponse.success(shop.products(u==null?null:u.getUsername(),category,keyword)));}
 @GetMapping("/vouchers/public") public ResponseEntity<?> publicVouchers(){return ResponseEntity.ok(ApiResponse.success(voucherService.publicList()));}
 @PostMapping("/vouchers/validate") public ResponseEntity<?> validateVoucher(@RequestBody Map<String,Object>b){@SuppressWarnings("unchecked")List<Map<String,Object>>rawItems=(List<Map<String,Object>>)b.get("items");List<VoucherService.CartLine>lines=rawItems==null?List.of():rawItems.stream().map(it->new VoucherService.CartLine(Long.valueOf(String.valueOf(it.get("productId"))),Double.parseDouble(String.valueOf(it.get("lineTotal"))))).toList();var r=voucherService.validate(String.valueOf(b.get("code")),lines);return ResponseEntity.ok(ApiResponse.success(Map.of("code",r.getKey().getCode(),"discount",r.getValue())));}
 @PostMapping("/vouchers/best") public ResponseEntity<?> bestVoucher(@RequestBody Map<String,Object>b){@SuppressWarnings("unchecked")List<Map<String,Object>>rawItems=(List<Map<String,Object>>)b.get("items");List<VoucherService.CartLine>lines=rawItems==null?List.of():rawItems.stream().map(it->new VoucherService.CartLine(Long.valueOf(String.valueOf(it.get("productId"))),Double.parseDouble(String.valueOf(it.get("lineTotal"))))).toList();var r=voucherService.best(lines);return ResponseEntity.ok(ApiResponse.success(r.map(x->Map.of("code",x.getKey().getCode(),"discount",x.getValue())).orElseGet(Map::of)));}
 @GetMapping("/cart") public ResponseEntity<?> cart(@AuthenticationPrincipal UserDetails u){return ResponseEntity.ok(ApiResponse.success(shop.cart(u.getUsername())));}
 @PostMapping("/cart") public ResponseEntity<?> add(@AuthenticationPrincipal UserDetails u,@RequestBody Map<String,Object>b){Long variantId=b.get("variantId")==null?null:Long.valueOf(String.valueOf(b.get("variantId")));shop.addCart(u.getUsername(),Long.valueOf(String.valueOf(b.get("productId"))),variantId,Integer.parseInt(String.valueOf(b.getOrDefault("quantity",1))));return ResponseEntity.ok(ApiResponse.success("Đã thêm vào giỏ"));}
 @PutMapping("/cart/{id}") public ResponseEntity<?> update(@AuthenticationPrincipal UserDetails u,@PathVariable Long id,@RequestBody Map<String,Object>b){shop.updateCart(u.getUsername(),id,Integer.parseInt(String.valueOf(b.get("quantity"))));return ResponseEntity.ok(ApiResponse.success("Đã cập nhật"));}
 @DeleteMapping("/cart/{id}") public ResponseEntity<?> remove(@AuthenticationPrincipal UserDetails u,@PathVariable Long id){shop.removeCart(u.getUsername(),id);return ResponseEntity.ok(ApiResponse.success("Đã xóa"));}
 @PostMapping("/orders") public ResponseEntity<?> checkout(@AuthenticationPrincipal UserDetails u,@RequestBody Map<String,Object>b){return ResponseEntity.ok(ApiResponse.success(shop.checkout(u.getUsername(),b)));}
 @GetMapping("/orders") public ResponseEntity<?> orders(@AuthenticationPrincipal UserDetails u){return ResponseEntity.ok(ApiResponse.success(shop.myOrders(u.getUsername())));}
 @GetMapping("/orders/{id}") public ResponseEntity<?> order(@AuthenticationPrincipal UserDetails u,@PathVariable Long id){return ResponseEntity.ok(ApiResponse.success(shop.order(u.getUsername(),id)));}
 @PostMapping("/orders/lookup") public ResponseEntity<?> lookup(@RequestBody Map<String,Object>b){return ResponseEntity.ok(ApiResponse.success(shop.lookupOrder(Long.valueOf(String.valueOf(b.get("orderId"))),String.valueOf(b.get("phone")))));}
 @PostMapping("/orders/guest-cancel/request-otp") public ResponseEntity<?> requestOtp(@RequestBody Map<String,Object>b){if(!otpEnabled)throw new RuntimeException("OTP email chưa được bật");Long id=Long.valueOf(String.valueOf(b.get("orderId")));String address=String.valueOf(b.getOrDefault("email","")).trim();var o=shop.guestOrder(id,address);String key=id+":"+address.toLowerCase();String code=otp.issue(key);email.sendOrderCancellationOtp(address,code);return ResponseEntity.ok(ApiResponse.success(Map.of("message","Đã gửi OTP tới email")));}
 @PostMapping("/orders/guest-cancel") public ResponseEntity<?> guestCancel(@RequestBody Map<String,Object>b){Long id=Long.valueOf(String.valueOf(b.get("orderId")));String address=String.valueOf(b.getOrDefault("email","")).trim();String code=String.valueOf(b.getOrDefault("otp",""));if(!otp.consume(id+":"+address.toLowerCase(),code))throw new RuntimeException("OTP không đúng hoặc đã hết hạn");return ResponseEntity.ok(ApiResponse.success(shop.cancelGuest(id,address),"Đã hủy đơn"));}
 @PostMapping("/orders/{id}/cancel") public ResponseEntity<?> cancel(@AuthenticationPrincipal UserDetails u,@PathVariable Long id){return ResponseEntity.ok(ApiResponse.success(shop.cancel(u.getUsername(),id)));}
 @GetMapping("/admin/products") @PreAuthorize("hasAuthority('ROLE_ADMIN')") public ResponseEntity<?> all(){return ResponseEntity.ok(ApiResponse.success(shop.allProducts()));}
 @PostMapping("/admin/products") @PreAuthorize("hasAuthority('ROLE_ADMIN')") public ResponseEntity<?> create(@RequestBody Product p){return ResponseEntity.ok(ApiResponse.success(shop.saveProduct(null,p)));}
 @PutMapping("/admin/products/{id}") @PreAuthorize("hasAuthority('ROLE_ADMIN')") public ResponseEntity<?> edit(@PathVariable Long id,@RequestBody Product p){return ResponseEntity.ok(ApiResponse.success(shop.saveProduct(id,p)));}
 @DeleteMapping("/admin/products/{id}") @PreAuthorize("hasAuthority('ROLE_ADMIN')") public ResponseEntity<?> hide(@PathVariable Long id){shop.hideProduct(id);return ResponseEntity.ok(ApiResponse.success("Đã ngừng bán"));}
 @GetMapping("/admin/orders") @PreAuthorize("hasAnyAuthority('ROLE_ADMIN','ROLE_STAFF')") public ResponseEntity<?> allOrders(){return ResponseEntity.ok(ApiResponse.success(shop.allOrders()));}
 @PutMapping("/admin/orders/{id}/status") @PreAuthorize("hasAnyAuthority('ROLE_ADMIN','ROLE_STAFF')") public ResponseEntity<?> status(@PathVariable Long id,@RequestBody Map<String,String>b){return ResponseEntity.ok(ApiResponse.success(shop.updateStatus(id,OrderStatus.valueOf(b.get("status")))));}
}
